language: C
compiler: gcc
dist: trusty

sudo: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - eval "$(curl -sL https://raw.githubusercontent.com/ryuichis/oclint-cpp-travis-ci-examples/master/oclint-ci-install.sh)"

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

  - sudo apt-get install -qq cppcheck
  - sudo apt-get install -qq zzuf
script:
    - make
    - ./demo < tests/valid.txt | grep "xxx@yyy.zzz"
    - ./demo < tests/error_name.txt | grep "Invalid"
    - ./demo < tests/error_ccn.txt | grep "Invalid"
    - ./demo < tests/error_exp.txt | grep "Invalid"
    - ./demo < tests/error_zip.txt | grep "Invalid"
    - ./demo < tests/error_price.txt | grep "Invalid"
